server:
  port: 8190
  servlet:
    context-path: /store-carts
integrations:
  product-service:
    url: http://localhost:8080/store
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
